"""Change vector_store_id to vector_store_ids in openai_assistant table

Revision ID: f2589428c1d0
Revises: 3389c67fdcb4
Create Date: 2025-07-10 11:18:21.223114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '018'
down_revision = '017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "openai_assistant",
        sa.Column("vector_store_ids", postgresql.ARRAY(sa.String()), nullable=True),
    )

    op.execute(
        """
        UPDATE openai_assistant
        SET vector_store_ids = ARRAY[vector_store_id]
        WHERE vector_store_id IS NOT NULL
    """
    )

    op.drop_column("openai_assistant", "vector_store_id")
    # ### end Alembic commands ###


def downgrade():
    # Add back the single vector_store_id column as nullable for safe data migration
    op.add_column(
        "openai_assistant",
        sa.Column(
            "vector_store_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,  # Allow nulls temporarily for safe migration
        ),
    )

    op.execute(
        """
        UPDATE openai_assistant
        SET vector_store_id = vector_store_ids[1]
        WHERE vector_store_ids IS NOT NULL AND array_length(vector_store_ids, 1) > 0
        """
    )

    op.drop_column("openai_assistant", "vector_store_ids")
