"""Alter unique constraint assistant table

Revision ID: 023
Revises: 022
Create Date: 2025-08-20 15:02:39.151977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "023"
down_revision = "022"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_openai_assistant_assistant_id", table_name="openai_assistant")
    op.create_index(
        op.f("ix_openai_assistant_assistant_id"),
        "openai_assistant",
        ["assistant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_project_assistant_id", "openai_assistant", ["project_id", "assistant_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_project_assistant_id", "openai_assistant", type_="unique")
    op.drop_index(
        op.f("ix_openai_assistant_assistant_id"), table_name="openai_assistant"
    )
    op.create_index(
        "ix_openai_assistant_assistant_id",
        "openai_assistant",
        ["assistant_id"],
        unique=True,
    )
    # ### end Alembic commands ###
