"""unique constraint on project_name and org id

Revision ID: 8725df286943
Revises: 38f0e8c8dc92
Create Date: 2025-08-27 12:22:36.633904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "024"
down_revision = "023"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_project_name_org_id", "project", ["name", "organization_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_project_name_org_id", "project", type_="unique")
    # ### end Alembic commands ###
