"""add source document id to document table

Revision ID: 0c9793b419a4
Revises: b79fc198879a
Create Date: 2025-08-25 13:48:26.542200

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0c9793b419a4'
down_revision = 'b79fc198879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('source_document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'document', 'document', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'source_document_id')
    # ### end Alembic commands ###
