"""Add column task_id to DocTransformationJob model

Revision ID: 0ef4e8a1d7db
Revises: 6ed6ed401847
Create Date: 2025-09-08 18:08:55.335182

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0ef4e8a1d7db'
down_revision = '6ed6ed401847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_transformation_job', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('openai_conversation_organization_id_fkey1', 'openai_conversation', type_='foreignkey')
    op.drop_constraint('openai_conversation_project_id_fkey1', 'openai_conversation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('openai_conversation_project_id_fkey1', 'openai_conversation', 'project', ['project_id'], ['id'])
    op.create_foreign_key('openai_conversation_organization_id_fkey1', 'openai_conversation', 'organization', ['organization_id'], ['id'])
    op.drop_column('doc_transformation_job', 'task_id')
    # ### end Alembic commands ###
