"""add source_document_id to document

Revision ID: 269675883ecf
Revises: e9dd35eff62c
Create Date: 2025-08-10 07:06:31.889406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '269675883ecf'
down_revision = 'e9dd35eff62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('source_document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'document', 'document', ['source_document_id'], ['id'])
    op.drop_constraint('openai_conversation_organization_id_fkey1', 'openai_conversation', type_='foreignkey')
    op.drop_constraint('openai_conversation_project_id_fkey1', 'openai_conversation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('openai_conversation_project_id_fkey1', 'openai_conversation', 'project', ['project_id'], ['id'])
    op.create_foreign_key('openai_conversation_organization_id_fkey1', 'openai_conversation', 'organization', ['organization_id'], ['id'])
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'source_document_id')
    # ### end Alembic commands ###
