"""Add is_deleted column in document

Revision ID: 42c4c8b22a09
Revises: 38f0e8c8dc92
Create Date: 2025-08-22 15:16:29.489991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "42c4c8b22a09"
down_revision = "38f0e8c8dc92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("project_id", sa.Integer(), nullable=False))
    op.add_column("document", sa.Column("is_deleted", sa.Boolean(), nullable=False))

    # Must Do  --> Think about how we will execute this migration on current DB
    # Dropping Owner id, adding values to project id column and more idk rn

    op.drop_constraint("document_owner_id_fkey", "document", type_="foreignkey")
    op.create_foreign_key(
        None, "document", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("document", "owner_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "document", type_="foreignkey")
    op.create_foreign_key(
        "document_owner_id_fkey",
        "document",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("document", "is_deleted")
    op.drop_column("document", "project_id")
    # ### end Alembic commands ###
