"""Config management tables

Revision ID: 4523c8d1253d
Revises: 6fe772038a5a
Create Date: 2025-11-13 11:56:57.233241

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4523c8d1253d'
down_revision = '6fe772038a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'deleted_at')
    )
    op.create_index(op.f('ix_config_name'), 'config', ['name'], unique=False)
    op.create_index(op.f('ix_config_project_id'), 'config', ['project_id'], unique=False)
    op.create_table('config_version',
    sa.Column('config_blob', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('commit_message', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'version')
    )
    op.create_index(op.f('ix_config_version_config_id'), 'config_version', ['config_id'], unique=False)


def downgrade():
    op.drop_index(op.f('ix_config_version_config_id'), table_name='config_version')
    op.drop_table('config_version')
    op.drop_index(op.f('ix_config_project_id'), table_name='config')
    op.drop_index(op.f('ix_config_name'), table_name='config')
    op.drop_table('config')
