"""Add prompt and version table

Revision ID: 757f50ada8ef
Revises: e9dd35eff62c
Create Date: 2025-08-14 11:45:07.186686

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '757f50ada8ef'
down_revision = 'e9dd35eff62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active_version', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_version'], ['prompt_version.id'], initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_name'), 'prompt', ['name'], unique=False)
    op.create_index(op.f('ix_prompt_project_id'), 'prompt', ['project_id'], unique=False)
    op.create_index('ix_prompt_project_id_is_deleted', 'prompt', ['project_id', 'is_deleted'], unique=False)
    op.create_table('prompt_version',
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commit_message', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version')
    )
    op.create_foreign_key(
        None,
        "prompt",
        "prompt_version",
        ["active_version"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    op.create_index(op.f('ix_prompt_version_prompt_id'), 'prompt_version', ['prompt_id'], unique=False)
    op.create_index('ix_prompt_version_prompt_id_is_deleted', 'prompt_version', ['prompt_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_version_prompt_id_is_deleted', table_name='prompt_version')
    op.drop_index(op.f('ix_prompt_version_prompt_id'), table_name='prompt_version')
    op.drop_table('prompt_version')
    op.drop_index('ix_prompt_project_id_is_deleted', table_name='prompt')
    op.drop_index(op.f('ix_prompt_project_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_name'), table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###
