"""add source_document_id to document

Revision ID: 794f79eac3ce
Revises: 38f0e8c8dc92
Create Date: 2025-08-22 10:49:04.020124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '794f79eac3ce'
down_revision = '38f0e8c8dc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('source_document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'document', 'document', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'source_document_id')
    # ### end Alembic commands ###
