"""add_db_comments

Revision ID: 8d3c3e8ce7b8
Revises: eed36ae3c79a
Create Date: 2025-12-10 13:33:44.172685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8d3c3e8ce7b8"
down_revision = "eed36ae3c79a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credential",
        "organization_id",
        existing_type=sa.INTEGER(),
        comment="Reference to the organization",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "project_id",
        existing_type=sa.INTEGER(),
        comment="Reference to the project",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="Flag indicating if this credential is currently active and usable",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "id",
        existing_type=sa.INTEGER(),
        comment="Unique ID for the credential",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "credential",
        "provider",
        existing_type=sa.VARCHAR(),
        comment="Provider name like 'openai', 'gemini'",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "credential",
        existing_type=sa.VARCHAR(),
        comment="Encrypted JSON string containing provider-specific API credentials",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "inserted_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Timestamp when the credential was created",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Timestamp when the credential was last updated",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credential",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Timestamp when the credential was last updated",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "inserted_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Timestamp when the credential was created",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "credential",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Encrypted JSON string containing provider-specific API credentials",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "provider",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Provider name like 'openai', 'gemini'",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Unique ID for the credential",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "credential",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Flag indicating if this credential is currently active and usable",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "project_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Reference to the project",
        existing_nullable=False,
    )
    op.alter_column(
        "credential",
        "organization_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Reference to the organization",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
