"""add_conversation_content_fields

Revision ID: ac721c972b10
Revises: f5628e3a9988
Create Date: 2025-07-12 16:53:33.798070

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "ac721c972b10"
down_revision = "f5628e3a9988"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "openai_conversation",
        sa.Column("user_question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "openai_conversation",
        sa.Column(
            "assistant_response", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "openai_conversation",
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "openai_conversation", sa.Column("input_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "openai_conversation", sa.Column("output_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "openai_conversation", sa.Column("total_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "openai_conversation",
        sa.Column("assistant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "openai_conversation", sa.Column("project_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "openai_conversation", sa.Column("organization_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("openai_conversation", "organization_id")
    op.drop_column("openai_conversation", "project_id")
    op.drop_column("openai_conversation", "assistant_id")
    op.drop_column("openai_conversation", "total_tokens")
    op.drop_column("openai_conversation", "output_tokens")
    op.drop_column("openai_conversation", "input_tokens")
    op.drop_column("openai_conversation", "model")
    op.drop_column("openai_conversation", "assistant_response")
    op.drop_column("openai_conversation", "user_question")
    # ### end Alembic commands ###
