"""Add FK constraint to user_id columns

Revision ID: b18795be76d1
Revises: 4da48b01f457
Create Date: 2025-06-05 15:29:59.330755

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "b18795be76d1"
down_revision = "4da48b01f457"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("apikey", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_foreign_key(
        None, "apikey", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "collection", "owner_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_foreign_key(
        None, "collection", "user", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("document", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_foreign_key(
        None, "document", "user", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "projectuser", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_foreign_key(
        None, "projectuser", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )

    op.alter_column(
        "credential", "credential", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(
        "credential_organization_id_fkey", "credential", type_="foreignkey"
    )
    op.drop_constraint("credential_project_id_fkey", "credential", type_="foreignkey")
    op.create_foreign_key(None, "credential", "project", ["project_id"], ["id"])
    op.create_foreign_key(
        None, "credential", "organization", ["organization_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projectuser", type_="foreignkey")
    op.alter_column("projectuser", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "document", type_="foreignkey")
    op.alter_column("document", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "credential", type_="foreignkey")
    op.drop_constraint(None, "credential", type_="foreignkey")
    op.create_foreign_key(
        "credential_project_id_fkey",
        "credential",
        "project",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "credential_organization_id_fkey",
        "credential",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "credential", "credential", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_constraint(None, "collection", type_="foreignkey")
    op.alter_column("collection", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "apikey", type_="foreignkey")
    op.alter_column("apikey", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
