"""added casbin rule

Revision ID: b5055f0b4a4d
Revises: 8d7a05fd0ad4
Create Date: 2025-04-09 13:45:43.511977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b5055f0b4a4d'
down_revision = '8d7a05fd0ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v0', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v3', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v4', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v5', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casbin_rule_ptype'), 'casbin_rule', ['ptype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casbin_rule_ptype'), table_name='casbin_rule')
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
