"""add source document id to document table

Revision ID: b5b9412d3d2a
Revises: 40307ab77e9f
Create Date: 2025-08-29 15:59:34.347031

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b5b9412d3d2a'
down_revision = '40307ab77e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('source_document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'document', 'document', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'source_document_id')
    # ### end Alembic commands ###
