"""Add storage_path column in project table

Revision ID: b79fc198879a
Revises: 42c4c8b22a09
Create Date: 2025-08-22 16:23:28.162616

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b79fc198879a'
down_revision = '42c4c8b22a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('storage_path', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'project', ['storage_path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'storage_path')
    # ### end Alembic commands ###
