"""create job table

Revision ID: be78247139f9
Revises: 6ed6ed401847
Create Date: 2025-09-18 13:00:23.212198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'be78247139f9'
down_revision = '6ed6ed401847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('job_type', sa.Enum('RESPONSE', name='jobtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('openai_conversation_project_id_fkey1', 'openai_conversation', type_='foreignkey')
    op.drop_constraint('openai_conversation_organization_id_fkey1', 'openai_conversation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('openai_conversation_organization_id_fkey1', 'openai_conversation', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key('openai_conversation_project_id_fkey1', 'openai_conversation', 'project', ['project_id'], ['id'])
    op.drop_table('job')
    # ### end Alembic commands ###
