"""add celery task id to doc transformation job table

Revision ID: c9cc68c3b6b9
Revises: ed1bae633059
Create Date: 2025-08-29 13:52:13.018075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c9cc68c3b6b9'
down_revision = 'ed1bae633059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_transformation_job', sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_transformation_job', 'celery_task_id')
    # ### end Alembic commands ###
