"""Add is_deleted column in assistant table

Revision ID: d4af4420f652
Revises: f2589428c1d0
Create Date: 2025-07-18 15:14:45.700564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4af4420f652'
down_revision = 'f2589428c1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'openai_assistant',
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE'))
    )
    op.add_column(
        'openai_assistant',
        sa.Column('deleted_at', sa.DateTime(), nullable=True)
    )
    # Remove the default (optional, to avoid future auto-defaults)
    op.alter_column('openai_assistant', 'is_deleted', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openai_assistant', 'deleted_at')
    op.drop_column('openai_assistant', 'is_deleted')
    # ### end Alembic commands ###
