"""added casbin rule

Revision ID: d923a89827eb
Revises: 77dc462dc6b0
Create Date: 2025-04-08 09:44:57.711016

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "d923a89827eb"
down_revision = "77dc462dc6b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casbin_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ptype", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("v0", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("v1", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("v2", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("v3", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("v4", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("v5", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_casbin_rule_ptype"), "casbin_rule", ["ptype"], unique=False
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("fname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "object_store_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document")
    op.drop_index(op.f("ix_casbin_rule_ptype"), table_name="casbin_rule")
    op.drop_table("casbin_rule")
    # ### end Alembic commands ###
