"""Config management tables

Revision ID: e51b082aa9b3
Revises: 219033c644de
Create Date: 2025-11-05 16:19:20.423398

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e51b082aa9b3'
down_revision = '219033c644de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_name'), 'config', ['name'], unique=False)
    op.create_index(op.f('ix_config_project_id'), 'config', ['project_id'], unique=False)
    op.create_table('config_version',
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('commit_message', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'version')
    )
    op.create_index(op.f('ix_config_version_config_id'), 'config_version', ['config_id'], unique=False)
    op.drop_constraint(op.f('openai_conversation_project_id_fkey1'), 'openai_conversation', type_='foreignkey')
    op.drop_constraint(op.f('openai_conversation_organization_id_fkey1'), 'openai_conversation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('openai_conversation_organization_id_fkey1'), 'openai_conversation', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('openai_conversation_project_id_fkey1'), 'openai_conversation', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_config_version_config_id'), table_name='config_version')
    op.drop_table('config_version')
    op.drop_index(op.f('ix_config_project_id'), table_name='config')
    op.drop_index(op.f('ix_config_name'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
