"""Config management tables

Revision ID: ecda6b144627
Revises: 633e69806207
Create Date: 2025-11-19 13:16:50.954576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ecda6b144627"
down_revision = "633e69806207"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_config_project_id_updated_at_active",
        "config",
        ["project_id", "updated_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_config_project_id_name_active",
        "config",
        ["project_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "config_version",
        sa.Column(
            "config_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "commit_message",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("config_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["config_id"], ["config.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "config_id", "version", name="uq_config_version_config_id_version"
        ),
    )
    op.create_index(
        "idx_config_version_config_id_version_active",
        "config_version",
        ["config_id", "version"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_config_version_config_id_version_active",
        table_name="config_version",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("config_version")
    op.drop_index(
        "uq_config_project_id_name_active",
        table_name="config",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "idx_config_project_id_updated_at_active",
        table_name="config",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("config")
    # ### end Alembic commands ###
