"""add openai_conversation table

Revision ID: f5628e3a9988
Revises: 3389c67fdcb4
Create Date: 2025-07-12 12:59:51.909268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "f5628e3a9988"
down_revision = "3389c67fdcb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openai_conversation",
        sa.Column("response_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "ancestor_response_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "previous_response_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("user_question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "assistant_response", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assistant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_openai_conversation_ancestor_response_id"),
        "openai_conversation",
        ["ancestor_response_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_openai_conversation_previous_response_id"),
        "openai_conversation",
        ["previous_response_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_openai_conversation_response_id"),
        "openai_conversation",
        ["response_id"],
        unique=False,
    )
    op.alter_column(
        "credential", "credential", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(
        "credential_organization_id_fkey", "credential", type_="foreignkey"
    )
    op.drop_constraint("credential_project_id_fkey", "credential", type_="foreignkey")
    op.create_foreign_key(None, "credential", "project", ["project_id"], ["id"])
    op.create_foreign_key(
        None, "credential", "organization", ["organization_id"], ["id"]
    )
    op.alter_column(
        "openai_assistant",
        "instructions",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_openai_assistant_assistant_id"),
        "openai_assistant",
        ["assistant_id"],
        unique=True,
    )
    op.drop_constraint(
        "openai_assistant_organization_id_fkey", "openai_assistant", type_="foreignkey"
    )
    op.drop_constraint(
        "openai_assistant_project_id_fkey", "openai_assistant", type_="foreignkey"
    )
    op.create_foreign_key(None, "openai_assistant", "project", ["project_id"], ["id"])
    op.create_foreign_key(
        None, "openai_assistant", "organization", ["organization_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "openai_assistant", type_="foreignkey")
    op.drop_constraint(None, "openai_assistant", type_="foreignkey")
    op.create_foreign_key(
        "openai_assistant_project_id_fkey",
        "openai_assistant",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "openai_assistant_organization_id_fkey",
        "openai_assistant",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_openai_assistant_assistant_id"), table_name="openai_assistant"
    )
    op.alter_column(
        "openai_assistant",
        "instructions",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "credential", type_="foreignkey")
    op.drop_constraint(None, "credential", type_="foreignkey")
    op.create_foreign_key(
        "credential_project_id_fkey",
        "credential",
        "project",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "credential_organization_id_fkey",
        "credential",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "credential", "credential", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(
        op.f("ix_openai_conversation_response_id"), table_name="openai_conversation"
    )
    op.drop_index(
        op.f("ix_openai_conversation_previous_response_id"),
        table_name="openai_conversation",
    )
    op.drop_index(
        op.f("ix_openai_conversation_ancestor_response_id"),
        table_name="openai_conversation",
    )
    op.drop_table("openai_conversation")
    # ### end Alembic commands ###
