"""Add intial casbin policies

Revision ID: fc2d7ddfa265
Revises: b5055f0b4a4d
Create Date: 2025-04-09 13:48:15.502779

"""
from alembic import op
import sqlalchemy as sa
import os, json
import sqlmodel.sql.sqltypes
from app.alembic.utils import update_casbin_policies


# revision identifiers, used by Alembic.
revision = 'fc2d7ddfa265'
down_revision = 'b5055f0b4a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    file_path = os.path.join(os.path.dirname(__file__), "../../core/rbac/rbac_policies.json")
    update_casbin_policies(conn, file_path)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Not needed as only adding policies data
    pass
    # ### end Alembic commands ###
